# Generated by Django 4.2.13 on 2024-06-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(max_length=20, unique=True)),
                ('specialization', models.CharField(choices=[('networks', 'networks'), ('software', 'software')], default='software', max_length=50, verbose_name='specialization')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to='professors.professor')),
                ('project_idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('students', models.ManyToManyField(related_name='groups', to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.studentgroup'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
