# Generated by Django 4.2.13 on 2024-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_studentgroup_students_studentgroup_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='students',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(related_name='groups', to='students.student'),
        ),
    ]
