# Generated by Django 4.2.13 on 2024-06-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_studentgroup_students_studentgroup_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
