# Generated by Django 4.2.13 on 2024-06-24 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentgroup_is_published_alter_studentgroup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='students',
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.studentgroup'),
        ),
    ]
