# Generated by Django 4.2.13 on 2024-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_studentgroup_students_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='id',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='is_published',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is Published'),
        ),
    ]
