# Generated by Django 4.2.13 on 2024-06-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_studentgroup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
