# Generated by Django 4.2.13 on 2024-08-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, height_field='height', null=True, upload_to='photos/projects', width_field='width')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('web', 'Web'), ('desktop', 'Desktop Program'), ('ai', 'AI Program'), ('full_stack', 'Full Stack App'), ('mobile', 'Mobile App')], default='web', max_length=20, verbose_name='project type')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('backlog', 'Backlog')], default='backlog', max_length=20, verbose_name='status')),
                ('FramworksFrontend', models.CharField(blank=True, choices=[('react', 'React'), ('angular', 'Angular'), ('vue.js', 'Vue.js'), ('svelte', 'Svelte'), ('bootstrap', 'Bootstrap')], default='react', max_length=20, null=True, verbose_name='Frontend')),
                ('FramworksBackend', models.CharField(blank=True, choices=[('django', 'Django'), ('node.js', 'Node.js'), ('express.js', 'Express.js'), ('ruby_on_rails', 'Ruby on Rails'), ('spring_boot', 'Spring Boot')], default='django', max_length=20, null=True, verbose_name='Backend')),
                ('FramworksMobileApps', models.CharField(blank=True, choices=[('flutter', 'Flutter'), ('react_native', 'React Native'), ('ionic', 'Ionic'), ('xamarin', 'Xamarin'), ('swift_ui', 'SwiftUI')], default='flutter', max_length=20, null=True, verbose_name='Mobile Apps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=1000)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project')),
            ],
        ),
    ]
