# Generated by Django 4.2.13 on 2024-06-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='idea',
        ),
    ]
