# Generated by Django 4.2.13 on 2024-06-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('phd_certificate', models.FileField(upload_to='certificates/')),
                ('phd_date', models.DateField()),
                ('specialization', models.CharField(choices=[('networks', 'networks'), ('software', 'software')], default='software', max_length=50, verbose_name='specialization')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
