# Generated by Django 4.2.13 on 2024-08-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phd_certificate', models.FileField(upload_to='certificates/')),
                ('phd_date', models.DateField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, choices=[('networks', 'networks'), ('software', 'software')], default='software', max_length=50, null=True, verbose_name='specialization')),
                ('years_of_experience', models.IntegerField(blank=True, default=5, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
