# Generated by Django 4.2.13 on 2024-08-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_professorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phd_certificate',
            field=models.FileField(upload_to='media/certificates/'),
        ),
    ]
