# Generated by Django 4.2.13 on 2024-08-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_professor_years_of_experience_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='professorProfile',
        ),
    ]
