# Generated by Django 4.2.13 on 2024-08-10 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('professors', '0004_delete_professorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='professor',
            name='phd_certificate',
            field=models.FileField(upload_to='certificates/'),
        ),
        migrations.CreateModel(
            name='professorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
