# Generated by Django 4.2.13 on 2024-08-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_remove_professor_years_of_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
