# Generated by Django 4.2.13 on 2024-08-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_professor_years_of_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='professorProfile',
        ),
    ]
