# Generated by Django 4.2.13 on 2024-08-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_delete_professorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
