# Generated by Django 4.2.13 on 2024-08-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0008_alter_professor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='phd_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
