# Generated by Django 4.2.13 on 2024-08-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0009_alter_professor_phd_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('networks', 'networks'), ('software', 'software')], default='software', max_length=50, null=True, verbose_name='specialization'),
        ),
    ]
