# Generated by Django 4.2.13 on 2024-08-11 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=19, help_text='The age must be between 18 and 100 years.', null=True, validators=[django.core.validators.MinValueValidator(19), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
